# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oppo/thortanium-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter A57,$(TARGET_DEVICE)),)

endif
